services:
  ned:
    image: ghcr.io/netwarlan/ned
    container_name: ned
    restart: "unless-stopped"
    environment:
      DISCORD_TOKEN: "${DISCORD_TOKEN}"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./config.yaml:/config/config.yaml:ro
      - /path/to/game-deployment-scripts:/scripts
    logging:
      options:
        max-size: "10m"
        max-file: "3"
